# Random number generator for multivariate Gaussian distribution

In [8]:
#Random number generator for multivariate Gaussian distribution

import numpy as np

u = np.array([1, 2, 3])
E = np.array([[3, -1, 1], [-1, 5, 3], [1, 3, 4]])
cholesky = np.linalg.cholesky(E)
for i in range(5):
    random = np.array(np.random.rand(3))
    x = np.dot(cholesky, random.T) + u
    print(x)

[1.61143516 2.74608659 4.34503718]
[1.11980685 3.97855725 4.71786367]
[2.28957648 2.91560996 4.94083791]
[1.80555875 2.01631744 4.15387593]
[2.52201015 1.72103348 4.29878479]
